// App phases - new flow
export type AppPhase =
	| 'main-question'
	| 'brain-dump'
	| 'core-definitions'
	| 'features'
	| 'summary'
	| 'complete';

// Core definitions for the product
export type CoreDefinitions = {
	ideaName: string;
	overallIdea: string;
	purpose: string;
	audience: string;
	productType: string;
};

// Options generated by AI for each core definition
export type CoreDefinitionOptions = {
	ideaName: string[];
	overallIdea: string[];
	purpose: string[];
	audience: string[];
	productType: string[];
};

// Feature with full details
export type Feature = {
	id: string;
	shortName: string;
	description: string;
	purpose: string;
	userStories: string[];
};

// The final PRD structure
export type PrdContent = {
	ideaName: string;
	overallIdea: string;
	purpose: string;
	audience: string;
	productType: string;
	features: Feature[];
	techStack: Array<{category: string; technology: string}>;
	nonFeatures: string[];
	constraints: string[];
	definitionOfDone: string;
};

// App state
export type AppState = {
	mainQuestion: string;
	brainDump: string;
	coreDefinitions: CoreDefinitions;
	features: Feature[];
};
